swagger: "2.0"
info:
  title: webservice API
  description: API description in Markdown.
  version: 1.0.0

basePath: /v1

consumes:
  - application/json
produces:
  - application/json

paths:
  /upload:
    post:
      summary: Uploads a file.
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: upfile
          type: file
          description: The file to upload.
      responses:
        200:
          description: OK
  /logistic_regression:
    post:
      summary: Runs logistic_regression
      parameters:
      - name: payload
        in: body
        schema:
          $ref: '#/definitions/LogisticRegression'
      responses:
        200:
          description: OK
  /random_forest:
    post:
        summary: Runs Random Forest
        parameters:
        - name: payload
          in: body
          schema:
            $ref: '#/definitions/RandomForest'
        responses:
          200:
            description: OK
  /svm:
    post:
        summary: Runs Random Forest
        parameters:
        - name: payload
          in: body
          schema:
            $ref: '#/definitions/SVM'
        responses:
          200:
            description: OK

definitions:
  File:
    type: object
    required:
      - filename
      - hasHeader
    properties:
      filename:
        type: string
        description: Name of file to use. Can use http paths
      headers:
        type: array
        items:
          type: string
        description: Column headers for this file.
      hasHeader:
        type: boolean  
        default: false
        description: Does the CSV file have a header
      classLabel:
        type: string
        description: Class Label - must be one of the columns in the header 
  LogisticRegression:
    allOf:
      - $ref: '#/definitions/File'
      - type: object
        properties:
          penalty:
            type: string 
            enum: 
            - l1
            - l2
            default: l2
            description: Penalty to apply
          C:
            type: number
            default: 0.1
            description: Control bias and variance of model
  RandomForest:
    allOf:
      - $ref: '#/definitions/File'
      - type: object
        properties:
          n_estimators:
            type: integer
            description: Type of n_estimators to apply
  SVM:
    allOf:
      - $ref: '#/definitions/File'
      - type: object
        properties:
          kernel:
            type: string
            enum:
              - linear
              - rbf
            default: linear
            description: Type of penalty to apply
          C:
            type: number
            default: 1.0
            description: Control bias and variance of model
